// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EncryptHelper is an autogenerated mock type for the EncryptHelper type
type EncryptHelper struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: password
func (_m *EncryptHelper) Decrypt(password string) string {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Encrypt provides a mock function with given fields: password
func (_m *EncryptHelper) Encrypt(password string) string {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Match provides a mock function with given fields: source, encryptedString
func (_m *EncryptHelper) Match(source string, encryptedString string) bool {
	ret := _m.Called(source, encryptedString)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(source, encryptedString)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
