// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoginHandler is an autogenerated mock type for the LoginHandler type
type LoginHandler struct {
	mock.Mock
}

// After provides a mock function with given fields:
func (_m *LoginHandler) After() {
	_m.Called()
}

// Before provides a mock function with given fields:
func (_m *LoginHandler) Before() {
	_m.Called()
}

// Do provides a mock function with given fields:
func (_m *LoginHandler) Do() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
