// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "oneday-infrastructure/login/domain"

	mock "github.com/stretchr/testify/mock"
)

// LoginUserRepo is an autogenerated mock type for the LoginUserRepo type
type LoginUserRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *LoginUserRepo) Add(_a0 *domain.LoginUserDO) {
	_m.Called(_a0)
}

// FindSmsCode provides a mock function with given fields: mobile
func (_m *LoginUserRepo) FindSmsCode(mobile string) string {
	ret := _m.Called(mobile)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(mobile)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOne provides a mock function with given fields: username, tenantId
func (_m *LoginUserRepo) GetOne(username string, tenantId string) *domain.LoginUserDO {
	ret := _m.Called(username, tenantId)

	var r0 *domain.LoginUserDO
	if rf, ok := ret.Get(0).(func(string, string) *domain.LoginUserDO); ok {
		r0 = rf(username, tenantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoginUserDO)
		}
	}

	return r0
}

// Update provides a mock function with given fields:
func (_m *LoginUserRepo) Update() {
	_m.Called()
}
