// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	tenant_domain "oneday-infrastructure/internal/pkg/tenant/domain"

	mock "github.com/stretchr/testify/mock"
)

// TenantRepo is an autogenerated mock type for the TenantRepo type
type TenantRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: do
func (_m *TenantRepo) Add(do *tenant_domain.TenantDO) tenant_domain.TenantDO {
	ret := _m.Called(do)

	var r0 tenant_domain.TenantDO
	if rf, ok := ret.Get(0).(func(*tenant_domain.TenantDO) tenant_domain.TenantDO); ok {
		r0 = rf(do)
	} else {
		r0 = ret.Get(0).(tenant_domain.TenantDO)
	}

	return r0
}

// FindByName provides a mock function with given fields: tenantName
func (_m *TenantRepo) FindByName(tenantName string) tenant_domain.TenantDO {
	ret := _m.Called(tenantName)

	var r0 tenant_domain.TenantDO
	if rf, ok := ret.Get(0).(func(string) tenant_domain.TenantDO); ok {
		r0 = rf(tenantName)
	} else {
		r0 = ret.Get(0).(tenant_domain.TenantDO)
	}

	return r0
}
